[package]
name = "toml_fix"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
toml_fix_helpers = {path="../toml_fix_helpers"}
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"
