[package]
name = "learning_conrod_game"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

[lib]

[dependencies]
derive_macros = {path="../derive_macros"}
derive_macros_helpers = {path="../derive_macros_helpers"}
learning_conrod_base = {path="../core"}
piston = {version = "0.42.0"}
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.60.0"
piston_window = "0.89.0"
glutin = "0.19.0"
conrod_core = "0.67.0"
conrod_piston = "0.67.0"
find_folder = "0.3.0"
rusttype = "0.8.1"
gfx_device_gl = "0.16.2"
gfx_core = "0.9.2"
vecmath = "0.3"
serde = {version = "1.0", features= ["derive"]}
ron="0.5.1"
