[package]
name = "learning_conrod_game"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

[lib]

[dependencies]
derive_macros = {path="../derive_macros"}
derive_macros_helpers = {path="../derive_macros_helpers"}
learning_conrod_core = {path="../core"}
piston2d-graphics = "0.30.0"
piston2d-opengl_graphics = "0.60.0"
piston_window = "0.89.0"
conrod_core = "0.69.0"
conrod_piston = "0.69.0"
serde = { version = "1.0.105", features = ["derive"] }
ron= "0.5.1"
log = "0.4.8"
