[package]
name = "derive_macros"
version = "0.1.0"
authors = ["BB20101997 <bennet-blessmann@t-online.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
derive_macros_helpers = {path="../derive_macros_helpers"}
proc-macro2 = "0.4"
syn = "0.14"
quote = "0.6"
