[package]
name = "learning_conrod_core"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_macros_helpers = {path = "../derive_macros_helpers"}
conrod_core = "0.69.0"
conrod_piston = "0.69.0"
piston_window = "0.89.0"
piston2d-opengl_graphics = "0.60.0"
ron= "0.5.1"
find_folder = "0.3.0"
log = "0.4.8"


[lib]
