[package]
name = "learning_conrod_core"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod_core = "0.67.0"
conrod_piston = "0.67.0"
piston = {version = "0.42.0"}
piston_window = "0.89.0"
piston2d-opengl_graphics = "0.60.0"
ron="0.5.1"
find_folder = "0.3.0"


[lib]
